[package]
name = "learn_cs"
version = "0.1.0"
edition = "2021"
authors = ["Zhifeng Wang zugz0wang@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
